image:
  file: .gitpod.Dockerfile

tasks:
  - init: dotnet --version
  - init: dotnet restore
  - command: dotnet build
  - command: dotnet test

vscode:
  extensions:
    - ms-dotnettools.csharp-for-open-vsx

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5001
    onOpen: ignore
