image:
  file: .gitpod.Dockerfile

tasks:
  - init: dotnet --info
  - command: dotnet restore && dotnet build
  - command: |
      export LT_USERNAME=${LT_USERNAME}
      export LT_ACCESS_KEY=${LT_ACCESS_KEY}
      dotnet test

vscode:
  extensions:
    - ms-dotnettools.csharp

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5001
    onOpen: ignore
