# Use a custom Dockerfile to set up the environment
image:
  dockerfile: .gitpod.Dockerfile

# Define tasks to automate during workspace startup
tasks:
  - init: |
      # Verify .NET SDK installation
      dotnet --info
    command: |
      # Restore and build project
      dotnet restore
      dotnet build
      # Run tests
      dotnet test

# Configure VS Code extensions
vscode:
  extensions:
    - ms-dotnettools.vscode-dotnet-sdk  # Use the community-maintained C# extension

# Enable prebuilds for branches and pull requests
github:
  prebuilds:
    branches: true
    pullRequests: true
    master: true

# Ports to expose for ASP.NET Core or other services
ports:
  - port: 5000  # ASP.NET Core HTTP
    onOpen: open-preview
  - port: 5001  # ASP.NET Core HTTPS
    onOpen: ignore
