image:
  file: .gitpod.Dockerfile

tasks:
  - init: dotnet --info
  - command: dotnet restore && dotnet build
  - command: dotnet test

vscode:
  extensions:
    - ms-dotnettools.vscode-dotnet-sdk

ports:
  - port: 5000
    onOpen: open-preview
  - port: 5001
    onOpen: ignore
