# Directly use the nightly SDK image for the workspace
image:
  dockerfile: .gitpod.Dockerfile

tasks:
  - name: Verify .NET SDK
    init: |
      # Check the .NET SDK version
      dotnet --version

  - name: Restore and Build Project
    command: |
      # Restore dependencies
      dotnet restore
      # Build the project
      dotnet build

  - name: Run Tests
    command: |
      # Run unit tests
      dotnet test

vscode:
  extensions:
    - ms-dotnettools.csharp-for-open-vsx       # Community-maintained C# extension from Open VSX

github:
  prebuilds:
    # Enable prebuilds for all branches and pull requests
    master: true
    branches: true
    pullRequests: true

ports:
  - port: 5000  # HTTP preview port for ASP.NET Core
    onOpen: open-preview
  - port: 5001  # HTTPS preview port
    onOpen: ignore
